vversion: '3.8'

services:
  imperator_v17:
    build: .
    container_name: imperator_v17
    restart: unless-stopped
    # Подгружаем токены из твоего файла .env
    env_file:
      - .env
    # Пробрасываем файлы наружу, чтобы они сохранялись на диске сервера
    volumes:
      - ./sessions:/app/sessions
      - ./imp17.db:/app/imp17.db
    # Ограничение логов, чтобы не забить диск сервера в Актобе
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
